name: Mock Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mock-job:
    runs-on: self-hosted
    steps:
      - name: Create a directory
        run: mkdir -p /Users/User11/Desktop/efrei/projets/devops/delivery-flow/mock-output

      - name: Hello World log
        run: echo "Hello World!"