name: Mock Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mock-job:
    runs-on: self-hosted
    steps:
      - name: Créer un dossier
        run: mkdir -p ${{ github.workspace }}/mock-output

      - name: Hello World log
        run: echo "Hello World!"
      
      - name: Afficher le workspace
        run: echo ${{ github.workspace }}